"""
train_action_classifier.py — PyTorch Exercise Classifier Training
==================================================================

Loads ``datasets/pose_dataset.csv`` (generated by ``extract_pose_data.py``),
trains a 3-hidden-layer MLP with BatchNorm and Dropout, and saves the best
checkpoint to ``models/exercise_classifier.pth``.

Target hardware: NVIDIA RTX 4500 Ada (lab workstation).
All tensors and the model are explicitly placed on CUDA.

Run:
    python scripts/train_action_classifier.py

Output:
    models/exercise_classifier.pth   (checkpoint dict with state_dict + metadata)
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = PROJECT_ROOT / "datasets" / "pose_dataset.csv"
MODEL_DIR = PROJECT_ROOT / "models"
SAVE_PATH = MODEL_DIR / "exercise_classifier.pth"

NUM_FEATURES = 99
HIDDEN_DIMS = [256, 128, 64]
DROPOUT = 0.25
BATCH_SIZE = 512
EPOCHS = 120
LR = 1e-3
WEIGHT_DECAY = 1e-4
VAL_SPLIT = 0.15
SEED = 42


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Model
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


class ExerciseClassifier(nn.Module):
    """MLP with BatchNorm + Dropout for 99-feature pose classification."""

    def __init__(
        self,
        n_features: int = NUM_FEATURES,
        n_classes: int = 6,
        hidden_dims: list[int] | None = None,
        dropout: float = DROPOUT,
    ) -> None:
        super().__init__()
        dims = hidden_dims or HIDDEN_DIMS
        layers: list[nn.Module] = []
        in_dim = n_features
        for h in dims:
            layers.extend([
                nn.Linear(in_dim, h),
                nn.BatchNorm1d(h),
                nn.ReLU(inplace=True),
                nn.Dropout(dropout),
            ])
            in_dim = h
        layers.append(nn.Linear(in_dim, n_classes))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Dataset
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


class PoseDataset(Dataset):
    def __init__(self, features: np.ndarray, labels: np.ndarray) -> None:
        self.X = torch.tensor(features, dtype=torch.float32)
        self.y = torch.tensor(labels, dtype=torch.long)

    def __len__(self) -> int:
        return len(self.y)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        return self.X[idx], self.y[idx]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Training
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def train() -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    if device.type != "cuda":
        print("[WARN] CUDA not available — training will be slow.", file=sys.stderr)

    # ── Load CSV ──────────────────────────────────────────────────────
    if not CSV_PATH.is_file():
        print(f"[ERROR] Dataset not found: {CSV_PATH}", file=sys.stderr)
        sys.exit(1)

    df = pd.read_csv(CSV_PATH)
    print(f"Loaded {len(df):,} samples from {CSV_PATH}")

    feature_cols = [c for c in df.columns if c != "label"]
    assert len(feature_cols) == NUM_FEATURES, (
        f"Expected {NUM_FEATURES} feature columns, got {len(feature_cols)}"
    )

    X = df[feature_cols].values.astype(np.float32)
    raw_labels = df["label"].values

    # ── Encode string labels → integer classes ────────────────────────
    unique_labels = sorted(set(raw_labels))
    label_to_idx = {lbl: i for i, lbl in enumerate(unique_labels)}
    idx_to_label = {i: lbl for lbl, i in label_to_idx.items()}
    num_classes = len(unique_labels)
    y = np.array([label_to_idx[lbl] for lbl in raw_labels], dtype=np.int64)

    print(f"Classes ({num_classes}): {unique_labels}")
    for lbl in unique_labels:
        count = (raw_labels == lbl).sum()
        print(f"  {lbl}: {count:,} samples")

    # ── Feature normalisation (z-score) ───────────────────────────────
    mean = X.mean(axis=0)
    std = X.std(axis=0) + 1e-8
    X = (X - mean) / std

    # ── Train / val split ─────────────────────────────────────────────
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=VAL_SPLIT, random_state=SEED, stratify=y,
    )
    print(f"Train: {len(X_train):,}  |  Val: {len(X_val):,}")

    train_ds = PoseDataset(X_train, y_train)
    val_ds = PoseDataset(X_val, y_val)

    train_dl = DataLoader(
        train_ds, batch_size=BATCH_SIZE, shuffle=True,
        num_workers=4, pin_memory=True,
    )
    val_dl = DataLoader(
        val_ds, batch_size=BATCH_SIZE * 2, shuffle=False,
        num_workers=4, pin_memory=True,
    )

    # ── Model / optimiser / loss ──────────────────────────────────────
    model = ExerciseClassifier(
        n_features=NUM_FEATURES,
        n_classes=num_classes,
        hidden_dims=HIDDEN_DIMS,
        dropout=DROPOUT,
    ).to(device)

    print(f"\nModel:\n{model}\n")
    total_params = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {total_params:,}")

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(
        model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

    # ── Training loop ─────────────────────────────────────────────────
    best_val_acc = 0.0
    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, EPOCHS + 1):
        # Train
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for xb, yb in train_dl:
            xb, yb = xb.to(device, non_blocking=True), yb.to(device, non_blocking=True)
            logits = model(xb)
            loss = criterion(logits, yb)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            train_loss += loss.item() * len(yb)
            train_correct += (logits.argmax(dim=1) == yb).sum().item()
            train_total += len(yb)

        scheduler.step()

        # Validate
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for xb, yb in val_dl:
                xb, yb = xb.to(device, non_blocking=True), yb.to(device, non_blocking=True)
                logits = model(xb)
                loss = criterion(logits, yb)
                val_loss += loss.item() * len(yb)
                val_correct += (logits.argmax(dim=1) == yb).sum().item()
                val_total += len(yb)

        t_acc = train_correct / train_total
        v_acc = val_correct / val_total
        t_loss = train_loss / train_total
        v_loss = val_loss / val_total

        marker = ""
        if v_acc > best_val_acc:
            best_val_acc = v_acc
            marker = " ← best"
            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "idx_to_label": idx_to_label,
                    "label_to_idx": label_to_idx,
                    "n_features": NUM_FEATURES,
                    "n_classes": num_classes,
                    "hidden_dims": HIDDEN_DIMS,
                    "dropout": DROPOUT,
                    "norm_mean": mean.tolist(),
                    "norm_std": std.tolist(),
                    "val_accuracy": v_acc,
                    "epoch": epoch,
                },
                SAVE_PATH,
            )

        print(
            f"Epoch {epoch:3d}/{EPOCHS}  "
            f"train_loss={t_loss:.4f}  train_acc={t_acc:.4f}  "
            f"val_loss={v_loss:.4f}  val_acc={v_acc:.4f}{marker}"
        )

    print(f"\nTraining complete.  Best validation accuracy: {best_val_acc:.4f}")
    print(f"Checkpoint saved: {SAVE_PATH}")


if __name__ == "__main__":
    train()
